###
GET localhost:8080/locations
Accept: application/json

###
GET localhost:8080/locations/2
Accept: application/json

###
GET localhost:8080/locations/6
Accept: application/json

###
POST localhost:8080/locations
Content-Type: application/json
Accept: application/json

{
  "name": "D",
  "lat": 6.0,
  "lon": -7.0
}

###
PUT localhost:8080/locations/2
Content-Type: application/json
Accept: application/json

{
  "name": "B",
  "lat": 50.0,
  "lon": 72.0
}

###
PUT localhost:8080/locations/6
Content-Type: application/json
Accept: application/json

{
  "name": "B",
  "lat": 5.0,
  "lon": 72.0
}

###
DELETE localhost:8080/locations/1

###
DELETE localhost:8080/locations/6

###
POST localhost:8080/locations
Content-Type: application/json
Accept: application/json

{
  "name": "B",
  "lat": 60.0,
  "lon": -7.0
}
