###
GET http://localhost:8080/api/movies
Content-Type: application/json

###
POST http://localhost:8080/api/movies
Content-Type: application/json
Accept: application/json

{
  "title": "A"
}

###
POST http://localhost:8080/api/movies/1/rating
Content-Type: application/json
Accept: application/json

{
  "rating": 4
}