###
GET localhost:8080/api/movies
Accept: application/json

###
GET localhost:8080/api/movies?title=A
Accept: application/json

###
GET localhost:8080/api/movies/1
Accept: application/json


###
POST localhost:8080/api/movies
Content-Type: application/json
Accept: application/json

{
  "title": "A",
  "length": 6.0
}

###
POST localhost:8080/api/movies/1/rating
Content-Type: application/json
Accept: application/json

{
  "rating": 5
}

###
DELETE localhost:8080/api/movies/1

###
GET localhost:8080/api/movies/5
Accept: application/json