###
GET localhost:8080/api/types

###
POST localhost:8080/api/appointments
Content-Type: application/json

{
  "taxNumber": "0123456789",
  "appointmentTime": {
    "startTime":"2021-07-19T12:00:00",
    "endTime": "2021-07-19T13:00:00"
  },
  "caseCode": "001"
}

###
POST localhost:8080/api/appointments
Content-Type: application/json

{
  "taxNumber": "0123456788",
  "appointmentTime": {
    "startTime":"2021-06-19T12:00:00",
    "endTime": "2021-07-19T13:00:00"
  },
  "caseCode": "006"
}